require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "bash",
    "cmake",
    "css",
    "csv",
    "dockerfile",
    "dot",
    "editorconfig",
    "gitcommit",
    "gitignore",
    "graphql",
    "html",
    "http",
    "javascript",
    "jsdoc",
    "json",
    "lua",
    "make",
    "markdown",
    "rust",
    "scheme",
    "scss",
    "sql",
    "toml",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
  },
  sync_install = false,
  auto_install = true,
  ignore_install = {},
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
  },
  modules = {},
}
